### ISSUE TITLE
Project has no license

### ISSUE THREAD

**Issue by sipickles** [disjunction/url-value-parser#2]
Its unusual for a Github project to have no license declaration. Is this intentional? It prohibits our use

**Comment by disjunction** [comment]
packgae.json claims:
`"license": "WTFPL"`

but you're right, I'll add it to the readme too

**Comment by weyert** [comment]
Would you be able to add this license? I have the same issue as @sipickles that I can't use it without a license

**Comment by weyert** [comment]
Thank you @disjunction for merging my PR with the LICENSE file. If you could release new package version which includes the file that would be awesome 🤗

**Comment by disjunction** [comment]
sorry, I completely forgot about it. Thanks for the nudge. Merged the PR and released on npm under version `2.0.3`

**Comment by weyert** [comment]
Thank you :)
